### ISSUE TITLE
Different activity orderings in case of identical timestamps

### ISSUE THREAD

**Issue by Nipi** [gertjanssenswillen/edeaR#12]
Hi Gert,

happy new year.

I'm working on bupaR and I noted some inconsistencies.

One of my issue last year was about the inconsistency of the information about the functions process_map() and precedence_matrix().

Now it's working well, but the information generated with the function start_activity() has not consistency yet.

Attached here some immages about the problem (Activities with letters - A, B, C).

Thanks for all.

![map](https://user-images.githubusercontent.com/18727013/34777503-d4f1a9fe-f61a-11e7-9541-7f74cbafb19b.PNG)

![matrix](https://user-images.githubusercontent.com/18727013/34777511-da79e60c-f61a-11e7-8ab4-633e531a4e63.PNG)

![start](https://user-images.githubusercontent.com/18727013/34777518-dee1dbb4-f61a-11e7-9368-4c726ab8f606.PNG)

**Comment by Nipi** [comment]
P.S.: the correct information is in the last immage

**Comment by gertjanssenswillen** [comment]
Hi

Best wishes for the new year ;)

This is a somewhat general issues in bupaR at the moment which occurs when multiple events in the same case have identical timestamp. The way in which these are sorted is currently different between some function (process_map/precedence matrix currenlty sort alphatically, while start_activities uses the original sorting of the data). 

I'm currently identifying the most optimal way to handle this from a technical point of view, probably by some configuration options in the eventlog() function, which will have to be propagated to all relevant functions (which might be some work). 

I'll let you know when I have an update on this

**Comment by Nipi** [comment]
Ok...thanks Gert.

**Comment by gertjanssenswillen** [comment]
Hi

I am testing a modification to the packages which will maintain the order of activities over different functions, even when timestamps are identical or missing. 

You can install the test-versions of the packages as follows:

library(devtools)
install_github("gertjanssenswillen/bupaR", ref = "eventlog-ordering")
install_github("gertjanssenswillen/edeaR", ref = "eventlog-ordering")
install_github("gertjanssenswillen/processmapR", ref = "eventlog-ordering")

The only thing that has visibly changed is the `order` argument in the `eventlog` function. Using this you can tell what order bupaR needs to use in case some activity instances have an identical start time or in case a timestamp is missing.

The order argument can have 3 different values
- `auto` (default) will always keep the activity instances in the same order in which they are originally in the data.frame
- `alphabetical` will order the activities by alphabet 
- `any_column_name`: using a column name in the data you can provide your own custom ordering (can be a numeric ranking or character field (in case it will use this alphabatically).

In order for this system to work, you need to recreate your event log object. The easiest is just running 

`data <- eventlog(data)`
or 
`data <- eventlog(data, order = ___)` (in case you don't want the default `auto` ordering

Once you have recreated your eventlog object, all functions should display activity instances in the same order (i.e. the precedence matrix, process map, start/and activity and every function which uses the notion of traces).

I hope this is clear for you? 

I'm keeping these branches separate for a little while because there still might be things which will break because of this, which I will solve a soon as possible. I hope to have a new stable release for cran at the end of this month.

Just let me know whether the results are now as expected.

Best
Gert

**Comment by Nipi** [comment]
Thank you Gert,

I’ll test it asap and send you a feedback. 

Thanks too much.

Niky

Inviato da iPhone

**Comment by gertjanssenswillen** [comment]
The ordering branch has been merged with master
